# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_teachingtip.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import qfluentwidgets

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(511, 166)
        self.verticalLayoutWidget = QtWidgets.QWidget(Frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 511, 166))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.lay = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.lay.setContentsMargins(20, 20, 20, 20)
        self.lay.setObjectName("lay")
        self.title = TitleLabel(self.verticalLayoutWidget)
        self.title.setObjectName("title")
        self.lay.addWidget(self.title, 0, QtCore.Qt.AlignHCenter)
        self.subtitle = SubtitleLabel(self.verticalLayoutWidget)
        self.subtitle.setObjectName("subtitle")
        self.lay.addWidget(self.subtitle, 0, QtCore.Qt.AlignHCenter)
        self.bl = BodyLabel(self.verticalLayoutWidget)
        self.bl.setObjectName("bl")
        self.lay.addWidget(self.bl)
        self.lay2 = QtWidgets.QHBoxLayout()
        self.lay2.setObjectName("lay2")
        self.bl2 = BodyLabel(self.verticalLayoutWidget)
        self.bl2.setObjectName("bl2")
        self.lay2.addWidget(self.bl2)
        self.link = HyperlinkLabel(self.verticalLayoutWidget)
        self.link.setUrl(QtCore.QUrl("https://github.com/XiaoshuDeXiaowo/AiTA"))
        self.link.setObjectName("link")
        self.lay2.addWidget(self.link)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lay2.addItem(spacerItem)
        self.lay.addLayout(self.lay2)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.title.setText(_translate("Frame", "人工智能旅行社客服"))
        self.subtitle.setText(_translate("Frame", "%s"))
        self.bl.setText(_translate("Frame", "目前仍处于测试阶段，功能可能不太稳定，遇到问题请理性反馈，谢谢！"))
        self.bl2.setText(_translate("Frame", "仓库链接："))
        self.link.setText(_translate("Frame", "https://github.com/XiaoshuDeXiaowo/AiTA"))
from qfluentwidgets import BodyLabel, HyperlinkLabel, SubtitleLabel, TitleLabel
