# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import qfluentwidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(991, 681)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 991, 681))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.lay = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.lay.setContentsMargins(20, 32, 20, 20)
        self.lay.setObjectName("lay")
        self.scroll = ScrollArea(self.verticalLayoutWidget)
        self.scroll.setStyleSheet("QScrollArea{background: transparent; border: none}")
        self.scroll.setWidgetResizable(True)
        self.scroll.setObjectName("scroll")
        self.scrollwidget = QtWidgets.QWidget()
        self.scrollwidget.setGeometry(QtCore.QRect(0, 0, 951, 429))
        self.scrollwidget.setStyleSheet("QWidget{background: transparent}")
        self.scrollwidget.setObjectName("scrollwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.scrollwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 951, 421))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.scrlay = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.scrlay.setContentsMargins(32, 0, 32, 0)
        self.scrlay.setObjectName("scrlay")
        self.hlay1 = QtWidgets.QHBoxLayout()
        self.hlay1.setObjectName("hlay1")
        self.quelabel1 = BodyLabel(self.verticalLayoutWidget_2)
        self.quelabel1.setObjectName("quelabel1")
        self.hlay1.addWidget(self.quelabel1, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.scrlay.addLayout(self.hlay1)
        self.hlay2 = QtWidgets.QHBoxLayout()
        self.hlay2.setObjectName("hlay2")
        self.head1 = PixmapLabel(self.verticalLayoutWidget_2)
        self.head1.setPixmap(QtGui.QPixmap(":/app/img/head.png"))
        self.head1.setObjectName("head1")
        self.hlay2.addWidget(self.head1, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.anslabel1 = BodyLabel(self.verticalLayoutWidget_2)
        self.anslabel1.setObjectName("anslabel1")
        self.hlay2.addWidget(self.anslabel1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlay2.addItem(spacerItem)
        self.scrlay.addLayout(self.hlay2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.scrlay.addItem(spacerItem1)
        self.scroll.setWidget(self.scrollwidget)
        self.lay.addWidget(self.scroll)
        self.sendlay = QtWidgets.QHBoxLayout()
        self.sendlay.setObjectName("sendlay")
        self.toggleTheme = qfluentwidgets.ToolButton(self.verticalLayoutWidget)
        self.toggleTheme.setObjectName("toggleTheme")
        self.toggleTheme.setIcon(qfluentwidgets.FluentIcon.CONSTRACT)
        self.sendlay.addWidget(self.toggleTheme, 0, QtCore.Qt.AlignBottom)
        self.Input = PlainTextEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Input.sizePolicy().hasHeightForWidth())
        self.Input.setSizePolicy(sizePolicy)
        self.Input.setObjectName("Input")
        self.sendlay.addWidget(self.Input)
        self.Send = qfluentwidgets.PrimaryToolButton(self.verticalLayoutWidget)
        self.Send.setObjectName("Send")
        self.Send.setIcon(qfluentwidgets.FluentIcon.UP)
        self.sendlay.addWidget(self.Send, 0, QtCore.Qt.AlignBottom)
        self.lay.addLayout(self.sendlay)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "人工智能旅行社客服 %s"))
        self.quelabel1.setText(_translate("Dialog", "Question Text......"))
        self.quelabel1.setProperty("lightCustomQss", _translate("Dialog", "QLabel{     font-size: 16px;     line-height: 28px;     color: #262626;     padding: 8px 20px;     white-space: pre-wrap;     background-color: #eff6ff;     border-radius: 14px;     position: relative; }"))
        self.quelabel1.setProperty("darkCustomQss", _translate("Dialog", "QLabel{     font-size: 16px;     line-height: 28px;     color: #f8faff;     padding: 8px 20px;     white-space: pre-wrap;     background-color: #414158;     border-radius: 14px;     position: relative; }"))
        self.anslabel1.setText(_translate("Dialog", "Answer Text......"))
        self.Send.setShortcut(_translate("Dialog", "Return"))
from qfluentwidgets import BodyLabel, PixmapLabel, PlainTextEdit, ScrollArea

